version: '3'

networks:
    otel:

services:

    collector:
        image: otel/opentelemetry-collector-contrib
        volumes:
            -   ./config/collector.yaml:/etc/otelcol-contrib/config.yaml
        networks:
            -   otel
        ports:
            # -   1888:1888 # pprof extension
            # -   8888:8888 # Prometheus metrics exposed by the collector
            # -   8889:8889 # Prometheus exporter metrics
            # -   13133:13133 # health_check extension
            # -   4317:4317 # OTLP gRPC receiver
            -   4318:4318 # OTLP http receiver
            # -   55679:55679 # zpages extension

    grafana:
        image: grafana/grafana
        volumes:
            -   ./config/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yml
        networks:
            -   otel
        ports:
            -   3000:3000

    prometheus:
        image: prom/prometheus
        volumes:
            -   ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
        networks:
            -   otel
        # ports:
        #     -   9090:9090

    tempo:
        image: grafana/tempo
        command: -config.file=/etc/tempo.yml
        volumes:
            -   ./config/tempo.yaml:/etc/tempo.yml
        networks:
            -   otel
        # ports:
        #     -   3200:3200   # tempo
        #     -   4317  # otlp grpc

    loki:
        image: grafana/loki
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            -   otel
        # ports:
        #     -   3100:3100
