receivers:
    otlp:
        protocols:
            http:
            grpc:

processors:
    batch:

exporters:
    otlp:
        endpoint: tempo:4317
        tls:
            insecure: true

    logging:
        loglevel: debug

    loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

    prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
            label1: value1

extensions:
    health_check: # responsible for responding to health check calls on behalf of the collector.
    pprof: # fetches the collector’s performance data
    zpages: # serves as an http endpoint that provides live debugging data about instrumented components.

service:
    extensions: [health_check, pprof, zpages]
    pipelines:
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]
        logs:
            receivers: [otlp]
            exporters: [loki]
